export const PROM_HISTOGRAM_UPLOAD = 'PROM_HISTOGRAM_UPLOAD';
export const PROM_HISTOGRAM_DOWNLOAD = 'PROM_HISTOGRAM_DOWNLOAD';
export const PROM_HISTOGRAM_DELETE = 'PROM_HISTOGRAM_DELETE';
export const PROM_COUNTER_ERRORS = 'PROM_COUNTER_ERRORS';
