name: Deploy to Cloud Run

on:
  push:
    branches:
      - backup/dev-2025-06-15

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: gmf-training

      - name: Set-Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: gmf-training

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker --quiet

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/gmf-training/dev-backend-web-server:latest .

      - name: Push to GCR
        run: |
          docker push gcr.io/gmf-training/dev-backend-web-server:latest

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy dev-backend-service \
            --image gcr.io/gmf-training/dev-backend-web-server:latest \
            --platform managed \
            --region asia-southeast1 \
            --allow-unauthenticated \
            --set-env-vars "NODE_ENV=production,PROTOCOL=${{ secrets.PROTOCOL }},HOST=${{ secrets.HOST }},FRONTEND_URL=${{ secrets.FRONTEND_URL_DEV }},BACKEND_URL=${{ secrets.BACKEND_URL_DEV }},DATABASE_URL=${{ secrets.DATABASE_URL_DEV }},QR_CODE_LINK=${{ secrets.QR_CODE_LINK_DEV }},ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }},REFRESH_TOKEN=${{ secrets.REFRESH_TOKEN }},VERIFICATION_TOKEN=${{ secrets.VERIFICATION_TOKEN }},MAIL_HOST=${{ secrets.MAIL_HOST }},MAIL_PORT=${{ secrets.MAIL_PORT }},MAIL_USER=${{ secrets.MAIL_USER }},MAIL_PASS=${{ secrets.MAIL_PASS }},APP_NAME=${{ secrets.APP_NAME }}"